# Generated by Django 4.2.2 on 2023-10-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='password',
        ),
    ]
