<<<<<<< HEAD
services:
- type: web
  name: django-quick-start
  env: python
  plan: starter
  buildCommand: ./build.sh
  startCommand: gunicorn dvs_automated.wsgi:application
  autoDeploy: false
  envVars:
    - key: WEB_CONCURRENCY
      value: 4
    - key: DATABASE_URL
      fromDatabase:
        name: django-quick-start
        property: connectionString
    - key: DJANGO_SECRET_KEY
      generateValue: true
    - key: DJANGO_ADMIN_URL
      generateValue: true
    - key: DJANGO_SETTINGS_MODULE
      value: dvs_automated.settings.production

databases:
- name: django-quick-start
  databaseName: django
=======
services:
- type: web
  name: django-quick-start
  env: python
  plan: starter
  buildCommand: ./build.sh
  startCommand: gunicorn dvs_automated.wsgi:application
  autoDeploy: false
  envVars:
    - key: WEB_CONCURRENCY
      value: 4
    - key: DATABASE_URL
      fromDatabase:
        name: django-quick-start
        property: connectionString
    - key: DJANGO_SECRET_KEY
      generateValue: true
    - key: DJANGO_ADMIN_URL
      generateValue: true
    - key: DJANGO_SETTINGS_MODULE
      value: dvs_automated.settings.production

databases:
- name: django-quick-start
  databaseName: django
>>>>>>> 0ca1209e5b00f9a2d369b035e42459cb31eb06d3
  user: django